const mutations = {
  IS_LOGIN: 'IS_LOGIN',
  IS_FIRST_LOGIN: 'IS_FIRST_LOGIN',
  SHOW_NOTIFY: 'SHOW_NOTIFY',
  TOGGLE_LOADER: 'TOGGLE_LOADER',
  SUCCESS_MESSAGE: 'SUCCESS_MESSAGE',
  ADD_SUBSCRIPTION: 'ADD_SUBSCRIPTION',
  SUBSCRIPTIONS: 'SUBSCRIPTIONS'
}

export default mutations
